name: 'airbyte_intercom'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configs
models: 
  airbyte_intercom: 
    +materialized: table 
    +schema: intercom_analytics   # 👈 dbt outputs go here
    tmp: 
      +materialized: view
      +schema: intercom_analytics

vars:
  # Raw Airbyte schema + database
  intercom_schema: AIRBYTE_SCHEMA
  intercom_database: AIRBYTE_DATABASE

  # Conversation-related sources
  conversations_conversation_rating: "{{ source('airbyte_intercom','conversation_rating') }}"
  conversations_sla_applied: "{{ source('airbyte_intercom','conversations_sla_applied') }}"
  conversations_assignee: "{{ source('airbyte_intercom','conversations_assignee') }}"
  conversations_statistics: "{{ source('airbyte_intercom','conversations_statistics') }}"
  conversations: "{{ source('airbyte_intercom','conversations') }}"

  # Other Intercom entities
  airbyte_intercom:
    admins: "{{ source('airbyte_intercom','admins') }}"
    companies: "{{ source('airbyte_intercom','companies') }}"
    contacts: "{{ source('airbyte_intercom','contacts') }}"
    conversation_parts: "{{ source('airbyte_intercom','conversation_parts') }}"
