name: 'airbyte_intercom'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configs
models: 
  airbyte_intercom: 
  +materialized: table 
  tmp: 
    +materialized: view

# Variables
vars:
  # Add your Snowflake schema + database overrides here
  intercom_schema: AIRBYTE_SCHEMA       # replace with the schema where Airbyte lands Intercom data
  intercom_database: AIRBYTE_DATABASE   # replace with your Snowflake database name

  # Source definitions for the package
  airbyte_intercom:
    admins: "{{ source('airbyte_intercom','admins') }}"
    companies: "{{ source('airbyte_intercom','companies') }}"
    companies_plan: "{{ source('airbyte_intercom','companies_plan') }}"
    contacts: "{{ source('airbyte_intercom','contacts') }}"
    conversation_parts: "{{ source('airbyte_intercom','conversation_parts') }}"
    conversations: "{{ source('airbyte_intercom','conversations') }}"
    conversations_assignee: "{{ source('airbyte_intercom','conversations_assignee') }}"
    conversations_conversation_rating: "{{ source('airbyte_intercom','conversations_conversation_rating') }}"
    conversations_sla_applied: "{{ source('airbyte_intercom','conversations_sla_applied') }}"
    conversations_statistics: "{{ source('airbyte_intercom','conversations_statistics') }}"
