{{ config(materialized='table') }}

with deduped as (
    {{ echo_dedupe_rows(
        ref('fct_intercom__echo_budget_items'),
        require_completed=true,
        completeness_fields=[
            'started_at',
            'completed_at',
            'auto_ug_at',
            'tags_applied',
            'vulcan_id',
            'phone',
            'email',
            'surplus',
            'vulcan_surplus',
            'total_unsecured_debt_vsapi',
            'total_household_income',
            'total_household_expenditure'
        ]
    ) }}
),
cleaned as (
    select
        {{ normalize_id('conversation_id') }} as conversation_id,
        {{ normalize_id('contact_id') }} as contact_id,
        completed_at,
        auto_ug_at,
        tags_applied,
        {{ normalize_id('vulcan_id_filled') }} as vulcan_id,
        phone,
        email,
        cast(total_unsecured_debt_vsapi as number(38,2)) as total_unsecured_debt,
        cast(total_household_income as number(38,2)) as total_household_income,
        cast(total_household_expenditure as number(38,2)) as total_household_expenditure,
        cast(surplus as number(38,2)) as surplus,
        cast(vulcan_surplus as number(38,2)) as vulcan_surplus,
        monthly_buildings_and_content_insurance_cost,
        monthly_child_maintenance_payment,
        monthly_childcare_costs,
        monthly_clothing_cost,
        monthly_council_tax_amount,
        monthly_electric_cost,
        monthly_energy_costs,
        monthly_fuel_costs,
        monthly_gas_cost,
        monthly_groceries_cost,
        monthly_hobbies_and_leisure_costs,
        monthly_internet_and_subscription_costs,
        monthly_life_insurance_cost,
        monthly_medical_costs,
        monthly_mortgage_amount,
        monthly_public_transport_costs,
        monthly_rent_amount,
        monthly_tv_licence_cost,
        monthly_tv_internet_and_subscription_costs,
        monthly_vehicle_finance_costs,
        monthly_vehicle_insurance_cost,
        monthly_vehicle_tax_cost,
        monthly_water_cost,
        buildings_and_contents,
        bundle_costs,
        car_maintenance,
        car_maintenance_cost,
        child_maintenance,
        clothing_and_footwear,
        council_tax,
        electric,
        fuel,
        gas,
        gas_and_electric,
        groceries,
        hair_costs,
        life_insurance,
        medical_prescriptions,
        mortgage,
        phone_costs,
        rent,
        tv_licence,
        vehicle_finance,
        vehicle_insurance,
        vehicle_tax,
        water,
        childcare_costs,
        hobbies_and_leisure,
        public_transport
    from deduped
)

select * from cleaned